[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -I src
  -DLV_LVGL_H_INCLUDE_SIMPLE

lib_deps =
  lovyan03/LovyanGFX @ ^1.1.12
  lvgl/lvgl @ ^8.3.11
  adafruit/Adafruit NeoPixel @ ^1.12.0

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; OTA Ayarlari (IP adresi cihaz baglaninca guncellenmelidir)
; upload_protocol = espota
; upload_port = 192.168.1.XXX
